feat: rearange workflow

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -9,16 +9,18 @@ on:
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
+env:
+  bucket: 's3://gucosme.dev/'
+  packageName: ${{ github.sha }}.zip
+
 jobs:
   # This workflow contains a single job called "build"
   build:
-    environment: 'prod'
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
 
+    environment: 'prod'
     env:
-      bucket: 's3://gucosme.dev/'
-      packageName: ${{ github.sha }}.zip
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
       AWS_REGION: sa-east-1
@@ -45,14 +47,16 @@ jobs:
           zip -r ${{ env.packageName }} *
           aws s3 cp ${{ env.packageName }} ${{ env.bucket }} --acl public-read
 
-      - name: create amplify env and deploy from s3
+      # this step will fail if the branch already exists
+      # so we return 'true' to ensure it'll always pass
+      - name: create amplify env
         run: |
           aws amplify create-branch \
             --app-id ${{ env.AMPLIFY_APP_ID }} \
-            --branch-name ${{ github.base_ref }}
+            --branch-name ${{ github.base_ref }} \
+            || true
 
       - name: deploy amplify from s3
-        if: always()
         run: |
           aws amplify start-deployment \
             --app-id ${{ env.AMPLIFY_APP_ID }} \
